# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ttf_sensor_api.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14ttf_sensor_api.proto\x12\x0ettf_sensor_api\"\x1b\n\x07Measure\x12\x10\n\x08\x64istance\x18\x01 \x01(\x05\"\"\n\x0fMeasureResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\\\n\x10TTFSensorService\x12H\n\nGetMeasure\x12\x17.ttf_sensor_api.Measure\x1a\x1f.ttf_sensor_api.MeasureResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ttf_sensor_api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MEASURE']._serialized_start=40
  _globals['_MEASURE']._serialized_end=67
  _globals['_MEASURERESPONSE']._serialized_start=69
  _globals['_MEASURERESPONSE']._serialized_end=103
  _globals['_TTFSENSORSERVICE']._serialized_start=105
  _globals['_TTFSENSORSERVICE']._serialized_end=197
# @@protoc_insertion_point(module_scope)
