// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ttf_sensor_api.proto

#include "ttf_sensor_api.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace ttf_sensor_api {

inline constexpr MeasureResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : success_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR MeasureResponse::MeasureResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct MeasureResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MeasureResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MeasureResponseDefaultTypeInternal() {}
  union {
    MeasureResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MeasureResponseDefaultTypeInternal _MeasureResponse_default_instance_;

inline constexpr Measure::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : distance_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Measure::Measure(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct MeasureDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MeasureDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MeasureDefaultTypeInternal() {}
  union {
    Measure _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MeasureDefaultTypeInternal _Measure_default_instance_;
}  // namespace ttf_sensor_api
static ::_pb::Metadata file_level_metadata_ttf_5fsensor_5fapi_2eproto[2];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_ttf_5fsensor_5fapi_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_ttf_5fsensor_5fapi_2eproto = nullptr;
const ::uint32_t TableStruct_ttf_5fsensor_5fapi_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::ttf_sensor_api::Measure, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::ttf_sensor_api::Measure, _impl_.distance_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::ttf_sensor_api::MeasureResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::ttf_sensor_api::MeasureResponse, _impl_.success_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::ttf_sensor_api::Measure)},
        {9, -1, -1, sizeof(::ttf_sensor_api::MeasureResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::ttf_sensor_api::_Measure_default_instance_._instance,
    &::ttf_sensor_api::_MeasureResponse_default_instance_._instance,
};
const char descriptor_table_protodef_ttf_5fsensor_5fapi_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\024ttf_sensor_api.proto\022\016ttf_sensor_api\"\033"
    "\n\007Measure\022\020\n\010distance\030\001 \001(\005\"\"\n\017MeasureRe"
    "sponse\022\017\n\007success\030\001 \001(\0102\\\n\020TTFSensorServ"
    "ice\022H\n\nGetMeasure\022\027.ttf_sensor_api.Measu"
    "re\032\037.ttf_sensor_api.MeasureResponse\"\000b\006p"
    "roto3"
};
static ::absl::once_flag descriptor_table_ttf_5fsensor_5fapi_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_ttf_5fsensor_5fapi_2eproto = {
    false,
    false,
    205,
    descriptor_table_protodef_ttf_5fsensor_5fapi_2eproto,
    "ttf_sensor_api.proto",
    &descriptor_table_ttf_5fsensor_5fapi_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_ttf_5fsensor_5fapi_2eproto::offsets,
    file_level_metadata_ttf_5fsensor_5fapi_2eproto,
    file_level_enum_descriptors_ttf_5fsensor_5fapi_2eproto,
    file_level_service_descriptors_ttf_5fsensor_5fapi_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_ttf_5fsensor_5fapi_2eproto_getter() {
  return &descriptor_table_ttf_5fsensor_5fapi_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_ttf_5fsensor_5fapi_2eproto(&descriptor_table_ttf_5fsensor_5fapi_2eproto);
namespace ttf_sensor_api {
// ===================================================================

class Measure::_Internal {
 public:
};

Measure::Measure(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ttf_sensor_api.Measure)
}
Measure::Measure(
    ::google::protobuf::Arena* arena, const Measure& from)
    : Measure(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE Measure::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void Measure::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.distance_ = {};
}
Measure::~Measure() {
  // @@protoc_insertion_point(destructor:ttf_sensor_api.Measure)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Measure::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void Measure::Clear() {
// @@protoc_insertion_point(message_clear_start:ttf_sensor_api.Measure)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.distance_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* Measure::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> Measure::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_Measure_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // int32 distance = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Measure, _impl_.distance_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Measure, _impl_.distance_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 distance = 1;
    {PROTOBUF_FIELD_OFFSET(Measure, _impl_.distance_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* Measure::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ttf_sensor_api.Measure)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 distance = 1;
  if (this->_internal_distance() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_distance(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ttf_sensor_api.Measure)
  return target;
}

::size_t Measure::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ttf_sensor_api.Measure)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 distance = 1;
  if (this->_internal_distance() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_distance());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData Measure::_class_data_ = {
    Measure::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* Measure::GetClassData() const {
  return &_class_data_;
}

void Measure::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<Measure*>(&to_msg);
  auto& from = static_cast<const Measure&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ttf_sensor_api.Measure)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_distance() != 0) {
    _this->_internal_set_distance(from._internal_distance());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Measure::CopyFrom(const Measure& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ttf_sensor_api.Measure)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Measure::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* Measure::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void Measure::InternalSwap(Measure* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.distance_, other->_impl_.distance_);
}

::google::protobuf::Metadata Measure::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ttf_5fsensor_5fapi_2eproto_getter, &descriptor_table_ttf_5fsensor_5fapi_2eproto_once,
      file_level_metadata_ttf_5fsensor_5fapi_2eproto[0]);
}
// ===================================================================

class MeasureResponse::_Internal {
 public:
};

MeasureResponse::MeasureResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ttf_sensor_api.MeasureResponse)
}
MeasureResponse::MeasureResponse(
    ::google::protobuf::Arena* arena, const MeasureResponse& from)
    : MeasureResponse(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE MeasureResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void MeasureResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.success_ = {};
}
MeasureResponse::~MeasureResponse() {
  // @@protoc_insertion_point(destructor:ttf_sensor_api.MeasureResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void MeasureResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void MeasureResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:ttf_sensor_api.MeasureResponse)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.success_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* MeasureResponse::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> MeasureResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_MeasureResponse_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // bool success = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(MeasureResponse, _impl_.success_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(MeasureResponse, _impl_.success_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool success = 1;
    {PROTOBUF_FIELD_OFFSET(MeasureResponse, _impl_.success_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* MeasureResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ttf_sensor_api.MeasureResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bool success = 1;
  if (this->_internal_success() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        1, this->_internal_success(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ttf_sensor_api.MeasureResponse)
  return target;
}

::size_t MeasureResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ttf_sensor_api.MeasureResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool success = 1;
  if (this->_internal_success() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData MeasureResponse::_class_data_ = {
    MeasureResponse::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* MeasureResponse::GetClassData() const {
  return &_class_data_;
}

void MeasureResponse::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<MeasureResponse*>(&to_msg);
  auto& from = static_cast<const MeasureResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ttf_sensor_api.MeasureResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_success() != 0) {
    _this->_internal_set_success(from._internal_success());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MeasureResponse::CopyFrom(const MeasureResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ttf_sensor_api.MeasureResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool MeasureResponse::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* MeasureResponse::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void MeasureResponse::InternalSwap(MeasureResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.success_, other->_impl_.success_);
}

::google::protobuf::Metadata MeasureResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ttf_5fsensor_5fapi_2eproto_getter, &descriptor_table_ttf_5fsensor_5fapi_2eproto_once,
      file_level_metadata_ttf_5fsensor_5fapi_2eproto[1]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace ttf_sensor_api
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
