// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ttf_sensor_api.proto

#include "ttf_sensor_api.pb.h"
#include "ttf_sensor_api.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace ttf_sensor_api {

static const char* TTFSensorService_method_names[] = {
  "/ttf_sensor_api.TTFSensorService/GetMeasure",
};

std::unique_ptr< TTFSensorService::Stub> TTFSensorService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< TTFSensorService::Stub> stub(new TTFSensorService::Stub(channel, options));
  return stub;
}

TTFSensorService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetMeasure_(TTFSensorService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status TTFSensorService::Stub::GetMeasure(::grpc::ClientContext* context, const ::ttf_sensor_api::Measure& request, ::ttf_sensor_api::MeasureResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ttf_sensor_api::Measure, ::ttf_sensor_api::MeasureResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetMeasure_, context, request, response);
}

void TTFSensorService::Stub::async::GetMeasure(::grpc::ClientContext* context, const ::ttf_sensor_api::Measure* request, ::ttf_sensor_api::MeasureResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ttf_sensor_api::Measure, ::ttf_sensor_api::MeasureResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetMeasure_, context, request, response, std::move(f));
}

void TTFSensorService::Stub::async::GetMeasure(::grpc::ClientContext* context, const ::ttf_sensor_api::Measure* request, ::ttf_sensor_api::MeasureResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetMeasure_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ttf_sensor_api::MeasureResponse>* TTFSensorService::Stub::PrepareAsyncGetMeasureRaw(::grpc::ClientContext* context, const ::ttf_sensor_api::Measure& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ttf_sensor_api::MeasureResponse, ::ttf_sensor_api::Measure, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetMeasure_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ttf_sensor_api::MeasureResponse>* TTFSensorService::Stub::AsyncGetMeasureRaw(::grpc::ClientContext* context, const ::ttf_sensor_api::Measure& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetMeasureRaw(context, request, cq);
  result->StartCall();
  return result;
}

TTFSensorService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TTFSensorService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TTFSensorService::Service, ::ttf_sensor_api::Measure, ::ttf_sensor_api::MeasureResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TTFSensorService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ttf_sensor_api::Measure* req,
             ::ttf_sensor_api::MeasureResponse* resp) {
               return service->GetMeasure(ctx, req, resp);
             }, this)));
}

TTFSensorService::Service::~Service() {
}

::grpc::Status TTFSensorService::Service::GetMeasure(::grpc::ServerContext* context, const ::ttf_sensor_api::Measure* request, ::ttf_sensor_api::MeasureResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace ttf_sensor_api

